### ISSUE TITLE
Support for Guzzle 6.x ?

### ISSUE THREAD

**Issue by Gounlaf** [namshi/cuzzle#8]
Hi,

Have you planned to support Guzzle 6.x ?
Looking at [Guzzle Upgrade Guide](https://github.com/guzzle/guzzle/blob/6.0.1/UPGRADING.md), lot of things have changed.

Any idea of time required ?

Thanks,
Regards

**Comment by mikedfunk** [comment]
+1

**Comment by njuljsong** [comment]
+1

Composer can not use multiple versions of the same package. We are using Guzzle 6 currently, but namshi/cuzzle is using Guzzle 4...

**Comment by cirpo** [comment]
Hi, I'm going to have a look this week. thanks

**Comment by Petah** [comment]
+1

**Comment by jaymecd** [comment]
+1, any updates?

**Comment by jaymecd** [comment]
I'd suggest _PSR-7_ **RequestInterface** support, rather stick to concrete implementation as Guzzle6

**Comment by cirpo** [comment]
@jaymecd sorry I was a bit busy in the last weeks, I'm going to work on it asap, thanks for the suggestion

**Comment by avindra** [comment]
+1

**Comment by timbroder** [comment]
:+1:

**Comment by odino** [comment]
Hi guys,

to be fair I dont think we're gonna have a lot of time to look at this in the upcoming weeks -- but would be glad to test and have a look at any PR that comes in ;-)

If anyone wants to start looking at this it would be great!

**Comment by odino** [comment]
support for guzzle 6 is in 2.0.0 -- have a try! :)

**Comment by jaymecd** [comment]
👍 well done
